---
title: "Page Visits Funnel Project"
output: html_notebook
---

```{r message = FALSE, error=TRUE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE, error=TRUE}
# load data
visits <- read_csv("visits.csv")
cart <- read_csv("cart.csv")
checkout <- read_csv("checkout.csv")
purchase <- read_csv("purchase.csv")
```

```{r error=TRUE}
# inspect data frames
head(visits)
head(cart)
head(checkout)
head(purchase)
```

```{r error=TRUE}
# remove the number column:
visits$...1 <- NULL
cart$...1 <- NULL
checkout$...1 <- NULL
purchase$...1 <- NULL

# define visits_cart here:
visit_cart <- visits %>%
left_join(cart)
 
# visit_cart <- left_join(visits, cart, by = c('user_id' = 'user_id'))

visit_cart
```

```{r error=TRUE}
# define total_visits here:
nrow(visits)

```

```{r error=TRUE}
# define visit_no_cart here:

visit_no_cart <- visit_cart %>% 
filter(is.na(cart_time)) 

nrow(visit_no_cart)

# The null rows means that the customer   
# visited the site but did not select a  
# product to place into the cart  
```

```{r error=TRUE}
# calculate visit_no_cart_percent here:

visit_no_cart_percent <- visit_no_cart %>%
summarize(visit_no_cart_percent = 1652/2000)

visit_no_cart_percent
```

```{r error=TRUE}
# define cart_checkout here:

cart_checkout <- cart %>%
left_join(checkout)
 
 
```

```{r error=TRUE}
# define total_carts here:
cart_checkout
nrow(cart_checkout)
 
```

```{r error=TRUE}
# define cart_no_checkout here:
cart_no_checkout <- cart_checkout %>%
filter(is.na(checkout_time))

nrow(cart_no_checkout)

```

```{r error=TRUE}
# calculate cart_no_checkout_percent here:
cart_no_checkout_percent <- cart_no_checkout %>%
summarize(cart_no_checkout_percent = 122/348)

cart_no_checkout_percent

```

```{r error=TRUE}
# define all_data here:

all_data <- visits %>%
left_join(cart) %>%
left_join(checkout) %>%
left_join(purchase)

head(all_data, 10)
```

```{r error=TRUE}
# define total_checkout here:

total_checkout <- nrow(all_data)
```

```{r error=TRUE}
# define checkout_no_purchase here:

checkout_no_purchase <- all_data %>%
filter(is.na(checkout_time))
total_checkout

nrow(checkout_no_purchase)
 
```

```{r error=TRUE}
# calculate checkout_no_purchase_percent here:

checkout_no_purchase_percent <- checkout_no_purchase %>% 
summarize(checkout_no_purchase_percent = 1774/2000)

checkout_no_purchase_percent
```

```{r error=TRUE}
# update all_data with time_to_purchase column here:

all_data <- all_data %>%
  mutate(time_to_purchase = purchase_time - visit_time)

```

```{r error=TRUE}
# inspect the updated all_data data frame here:

head(all_data)
```

```{r error=TRUE}
# define time_to_purchase here:

time_to_purchase <- all_data %>%
  summarize(mean_time = mean(time_to_purchase, na.rm = TRUE))
time_to_purchase
 
```
